### ISSUE TITLE
bug: Window filter records with context_attributes not working

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [adempiere/adempiere-gRPC-Server#37]
1. Open `Business Partner` window.
2. Select record.
3. Select any tab child to load records.

https://user-images.githubusercontent.com/20288327/151908490-8f7daddd-b8db-4115-b657-2521997ba5b6.mp4

The id of the business partner is sent to filter the records in `context_attributes`, but it shows all the records contained in the table.

http://localhost:8085/api/adempiere/user-interface/window/entities?window_uuid=a520de12-fb40-11e8-a479-7a0060f0aa01&tab_uuid=a49f9fe6-fb40-11e8-a479-7a0060f0aa01&context_attributes[]={"column_name":"C_BPartner_ID","value":1000000}&token=db548a1b-c629-4381-bdb0-232ef79a7aae&language=es

**Comment by yamelsenih** [comment]
already fixed with 2.5.7 version of gRPC-API, also the URL is wrong. Here a correct:

http://0.0.0.0:8085/api/adempiere/user-interface/window/entities?window_uuid=a520de12-fb40-11e8-a479-7a0060f0aa01&tab_uuid=a49f9fe6-fb40-11e8-a479-7a0060f0aa01&filters=[{"column_name":"C_BPartner_ID","value":1000000}]&token=79debb5c-0842-450d-8f1c-663b98d1efc2&language=es
